# Generated by Django 6.0 on 2026-01-28 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_user'),
        ('userpage', '0002_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10)])),
                ('status', models.CharField(default='In process', max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Esewa', 'Esewa'), ('Stripe', 'Stripe')], max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
